#pragma once

#define IDI_APPICON 1
#define IDC_TABCONTROL 1000

#define IDR_ACCELERATORS 3

/* Menu commands */
#define IDM_FILE_NEW 2000
#define IDM_FILE_CLOSE 2001
#define IDM_EDIT_UNDO 2010
#define IDM_EDIT_REDO 2011
#define IDM_EDIT_CUT 2012
#define IDM_EDIT_COPY 2013
#define IDM_EDIT_PASTE 2014
#define IDM_EDIT_DELETE 2015
#define IDM_EDIT_SELECTALL 2016
#define IDM_VIEW_FULLSCREEN 2020
#define IDM_HELP_SETTINGS 2029
#define IDM_HELP_HELP 2030
#define IDM_HELP_ABOUT 2031

#define IDD_INFO 10
#define IDD_NETSTAT 11
#define IDD_PING 12
#define IDD_LOOKUP 13
#define IDD_TRACEROUTE 14
#define IDD_WHOIS 15
#define IDD_FINGER 16
#define IDD_PORTSCAN 17
#define IDD_SPEED 18
#define IDD_SETTINGS 19
#define IDD_ABOUT 20
#define IDD_LANSCAN 21

/* Info tab */
#define IDC_INFO_IFACE_COMBO 100
#define IDC_INFO_MAC 101
#define IDC_INFO_IP 102
#define IDC_INFO_SPEED 103
#define IDC_INFO_STATUS 104
#define IDC_INFO_MTU 105
#define IDC_INFO_RXPACKETS 106
#define IDC_INFO_RXERR 107
#define IDC_INFO_TXPACKETS 108
#define IDC_INFO_TXERR 109
#define IDC_INFO_LABEL_SELECT 120
#define IDC_INFO_GROUP_IFACE 121
#define IDC_INFO_LABEL_MAC 122
#define IDC_INFO_LABEL_IP 123
#define IDC_INFO_LABEL_SPEED 124
#define IDC_INFO_LABEL_STATUS 125
#define IDC_INFO_LABEL_MTU 126
#define IDC_INFO_GROUP_STATS 127
#define IDC_INFO_LABEL_RXPACKETS 128
#define IDC_INFO_LABEL_RXERR 129
#define IDC_INFO_LABEL_TXPACKETS 130
#define IDC_INFO_LABEL_TXERR 131

/* Netstat tab */
#define IDC_NET_RADIO_ROUTE 200
#define IDC_NET_RADIO_STATS 201
#define IDC_NET_RADIO_CONN 202
#define IDC_NET_RUN 203
#define IDC_NET_OUTPUT 204

/* Ping tab */
#define IDC_PING_ADDR 300
#define IDC_PING_LIMIT_CHK 301
#define IDC_PING_COUNT 302
#define IDC_PING_BTN 303
#define IDC_PING_OUTPUT 304
#define IDC_PING_LABEL_ADDR 320
#define IDC_PING_LABEL_PINGS 321

/* Lookup tab */
#define IDC_LOOKUP_ADDR 400
#define IDC_LOOKUP_TYPE 401
#define IDC_LOOKUP_BTN 402
#define IDC_LOOKUP_OUTPUT 403
#define IDC_LOOKUP_LABEL_ADDR 420
#define IDC_LOOKUP_LABEL_TYPE 421

/* Traceroute tab */
#define IDC_TRACE_ADDR 500
#define IDC_TRACE_BTN 501
#define IDC_TRACE_OUTPUT 502
#define IDC_TRACE_LABEL_ADDR 520

/* Whois tab */
#define IDC_WHOIS_ADDR 600
#define IDC_WHOIS_SERVER 601
#define IDC_WHOIS_BTN 602
#define IDC_WHOIS_OUTPUT 603
#define IDC_WHOIS_LABEL_ADDR 620
#define IDC_WHOIS_LABEL_SERVER 621

/* Finger tab */
#define IDC_FINGER_ADDR 700
#define IDC_FINGER_BTN 701
#define IDC_FINGER_OUTPUT 702
#define IDC_FINGER_LABEL_ADDR 720

/* Port scan tab */
#define IDC_SCAN_ADDR 800
#define IDC_SCAN_START 801
#define IDC_SCAN_END 802
#define IDC_SCAN_BTN 803
#define IDC_SCAN_PROGRESS 804
#define IDC_SCAN_OUTPUT 805
#define IDC_SCAN_WARNING 806
#define IDC_SCAN_LABEL_ADDR 820
#define IDC_SCAN_LABEL_BETWEEN 821
#define IDC_SCAN_LABEL_AND 822

/* Speed tab */
#define IDC_SPEED_PING 900
#define IDC_SPEED_DOWN 901
#define IDC_SPEED_UP 902
#define IDC_SPEED_STATUS 903
#define IDC_SPEED_PROGRESS 904
#define IDC_SPEED_BTN 905
#define IDC_SPEED_LABEL_INTRO 920
#define IDC_SPEED_GROUP_PING 921
#define IDC_SPEED_GROUP_DOWN 922
#define IDC_SPEED_GROUP_UP 923

/* Settings dialog */
#define IDC_SETTINGS_LABEL_LANGUAGE 950
#define IDC_SETTINGS_LANG_COMBO 951
#define IDC_SETTINGS_CLOSE 952

/* About dialog */
#define IDC_ABOUT_TITLE 960
#define IDC_ABOUT_VERSION 961
#define IDC_ABOUT_LICENSE_LABEL 962
#define IDC_ABOUT_LICENSE_TEXT 963
#define IDC_ABOUT_DISCLAIMER_TITLE 964
#define IDC_ABOUT_DISCLAIMER_BODY 965
#define IDC_ABOUT_CLOSE 966

/* LAN Scan tab */
#define IDC_LANSCAN_LABEL_IFACE 1100
#define IDC_LANSCAN_IFACE_COMBO 1101
#define IDC_LANSCAN_BTN 1102
#define IDC_LANSCAN_PROGRESS 1103
#define IDC_LANSCAN_LIST 1104

/* Worker-thread -> UI messages, WM_APP-based, one range per tab. */
#define WM_APP_PING_LINE (WM_APP + 1)
#define WM_APP_PING_DONE (WM_APP + 2)
#define WM_APP_TRACE_HOP (WM_APP + 3)
#define WM_APP_TRACE_DONE (WM_APP + 4)
#define WM_APP_SCAN_RESULT (WM_APP + 5)
#define WM_APP_SCAN_PROGRESS (WM_APP + 6)
#define WM_APP_SCAN_DONE (WM_APP + 7)
#define WM_APP_TEXT_LINE (WM_APP + 8)
#define WM_APP_TEXT_DONE (WM_APP + 9)
#define WM_APP_SPEED_UPDATE (WM_APP + 10)
#define WM_APP_SPEED_DONE (WM_APP + 11)
#define WM_APP_LANSCAN_HOST (WM_APP + 12)
#define WM_APP_LANSCAN_PROGRESS (WM_APP + 13)
#define WM_APP_LANSCAN_DONE (WM_APP + 14)
#define WM_APP_LANSCAN_IPV6 (WM_APP + 15)
